version: '3.8'

services:
  # Aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unijovem-backend-app
    ports:
      - "8080:8080"
    environment:
      # Usar o banco Neon que já está configurado no properties
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://ep-noisy-block-aclvrlqj-pooler.sa-east-1.aws.neon.tech:5432/unijovem?sslmode=require}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-neondb_owner}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-npg_GV9f3mStQvhZ}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

      # Pool de conexões (conforme seu properties)
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=600000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000

      # JPA Configuration (conforme seu properties)
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_JPA_OPEN_IN_VIEW=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS=false
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

      # Server configuration
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/api

      # JSON configuration
      - SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS=false
      - SPRING_JACKSON_TIME_ZONE=America/Sao_Paulo
      - SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS=false

      # Timezone
      - TZ=America/Sao_Paulo

      # JVM Options
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/parametros/existem"]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 3